# Generated by Django 4.2.7 on 2023-12-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(max_length=5)),
                ('npk', models.FloatField(max_length=5)),
                ('moisture', models.FloatField(max_length=5)),
                ('timestamp_field', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
